### ISSUE TITLE
License, please.

### ISSUE THREAD

**Issue by pragmatrix** [Brooooooklyn/rust-skia#4]
Hi, first, great work!, I am quite surprised to see that the binding generation works for C++ header files, and I would like to give that a shot for creating up to date Skia bindings, primarily I am interested in the Vulkan backend. 

With a few hurdles, I was able to generate the bindings (including Vulkan support) on Ubuntu 18 after I failed to get everything working on Windows via msys (my primary development environment): clang 7.0.1 was not be to consume the Skia header files, many spurious errors were popping up, and I got confused about the include directories and their order, so I postponed that, and now I try to just use the Ubuntu generated bindings on windows.

Anyway, that's just to offer a bit of my motivational ground and progress, but to continue I'd like to see a license to be on the safe side, thanks.

**Comment by pragmatrix** [comment]
Update: I've managed to generate the bindings (though with 35 test errors) and run the hello program on windows.

**Comment by Brooooooklyn** [comment]
Oh,that's great. I will update License file soon.
> I've managed to generate the bindings (though with 35 test errors)

This erros is shown in osx too, it seems like a behavior of `bindgen`.

> I would like to give that a shot for creating up to date Skia bindings, primarily I am interested in the Vulkan backend

So, do you want develop this project with me as a collaborator?

**Comment by pragmatrix** [comment]
> So, do you want develop this project with me as a collaborator?

Ok, thanks for the license and the invitation, let's see if we can pull this off.
